### ISSUE TITLE
Need Help on how to use it

### ISSUE THREAD

**Issue by bionimic** [likewinter/queue-throttle#3]
Hi @likewinter 

I've tried to this in my project but at some point it paused my queues
Could u please provide a full example on how to use this?

unfortunately when it reaches the throttle limit (500 request per minute) it will pause the whole queue. so how to unpause it? 

Thanks!

**Comment by bionimic** [comment]
please help! :(

**Comment by likewinter** [comment]
It pause not the whole queue but the pipe (in terms of beanstalkd) where you are throttling. So you need to have one pipe per each job which you are want to throttle.

FYI there is native implementation of throttling in modern version of Laravel and it’s agnostic to queue driver while my package works only with beanstalk
https://laravel.com/docs/5.8/queues#rate-limiting

**Comment by bionimic** [comment]
Oh. Noted. Tq
